"""estado y precio congelado en pedidos y revocaciones

Revision ID: e1a124229f8e
Revises: c365c2d9b8ee
Create Date: 2026-09-14 08:28:46.980873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a124229f8e'
down_revision: Union[str, Sequence[str], None] = 'c365c2d9b8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_revocacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_revocacion_codigo'), 'solicitudes_revocacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_solicitudes_revocacion_id'), 'solicitudes_revocacion', ['id'], unique=False)
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.add_column('pedidos', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('pedidos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'fecha_baja')
    op.drop_column('usuarios', 'activo')
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('pedidos', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('pedidos', 'creado_en')
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_solicitudes_revocacion_id'), table_name='solicitudes_revocacion')
    op.drop_index(op.f('ix_solicitudes_revocacion_codigo'), table_name='solicitudes_revocacion')
    op.drop_table('solicitudes_revocacion')
    # ### end Alembic commands ###
